[tool.pyright]

typeCheckingMode = "strict"
exclude=["build/*"]
venv="venv"
reportUnknownMemberType = "information"
reportUnknownVariableType = "warning"
reportUnknownArgumentType = "information"
reportMissingTypeArgument = "information"
reportUnusedImport = "information"
reportUnnecessaryIsInstance = "information"
reportIncompatibleVariableOverride = "none"
reportMissingTypeStubs="information"
reportPrivateImportUsage="information"
